### ISSUE TITLE
Mejora para la navegación en páginas dinámicas

### ISSUE THREAD

**Issue by jonalvarezz** [soyalextreme/avo-store#1]
Hola @soyalextreme 😁

Hiciste un trabajo fantástico y revisando el proyecto noté que al dar click en un producto está sucediendo una recarga completa de la página, cuando podría ser tipo Single Page Application (SPA).

La razón es por la que esto pasa es porque [`Link` necesita el parámetro de `as` y de `href` para páginas dinámicas](https://nextjs.org/docs/routing/introduction#linking-between-pages).

Así que, aquí:
https://github.com/soyalextreme/avo-store/blob/2262121af7555cf23284953dfdf157edc9275615/components/CardProducts/index.tsx#L34

Debería ser como:
```jsx
<ButtonRef title="More Info" as={`/product/${product.id}`} href="/product/[id]" />
```

Consecuentemente debes ajustar `ButtonRef` para aceptar la propiedad `as` también :)

Si haces este cambio el cambio de página será mucho más rápido!

**Enlaces:** 
[Linking pages in Next.js](https://nextjs.org/docs/routing/introduction#linking-between-pages)

**Comment by soyalextreme** [comment]
Muchísimas gracias! Ya lo solucione. 
Fue un error que intente solucionar de muchas maneras y la solución era mucho mas simple.
